name: Publish

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Node version
        uses: actions/setup-node@v3
        with:
          node-version: 16
          
      # - name: Install dependencies
      #   run: yarn install --frozen-lockfile
      #   env:
      #     DETECT_CHROMEDRIVER_VERSION: true
          
      - name: Create Changelog
        run: |
          git log $(git describe --tags --abbrev=0)..HEAD --oneline &> ${{ github.workspace }}-CHANGELOG.txt
          cat ${{ github.workspace }}-CHANGELOG.txt
          
      - name: Setup Git
        run: |
          git config --global user.name "stateful-wombot"
          git config --global user.email "christian+github-bot@stateful.com"
          
      - name: Get Current Version Number
        run: |
          CURRENT_VERSION=$(cat package.json | jq .version | cut -d'"' -f 2)
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
          
      
        
      - name: Compile New Version (Stable)
        run: |
          RELEASE_VERSION=$(npx semver $CURRENT_VERSION -i patch)
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          echo "Bump to $RELEASE_VERSION"
        
      - name: Version Package
        run: |
          npm version $RELEASE_VERSION
          git tag -a $RELEASE_VERSION -m "$RELEASE_VERSION"
          
      
      - name: Package Extension (Stable)
        run: npm i --save-dev @vscode/vsce
        
      - run: npx vsce package $RELEASE_VERSION --no-git-tag-version --no-update-package-json -o "./marquee-$RELEASE_VERSION.vsix" ${{ github.event.inputs.additionalFlags }}
        
        
      # - name: Push Tags
      #   run: |
      #     git log -1 --stat
      #     git push origin main --tags
      # - run: |
      #     export GIT_TAG=$(git describe --tags --abbrev=0)
      #     echo "GIT_TAG=$GIT_TAG" >> $GITHUB_ENV
          
      - name: GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./marquee-*"
          bodyFile: ${{ github.workspace }}-CHANGELOG.txt
          tag: ${{ env.GIT_TAG }}
          prerelease: false
